### ISSUE TITLE
If the model hasn't tokenizer.json file, what should I do?

### ISSUE THREAD

**Issue by wolf-li** [mlc-ai/tokenizers-cpp#13]
Not all model in huggingface hub has tokenizer.json  file such like Marian model. 
'tokenizer_config.json',
 'special_tokens_map.json',
 'vocab.json',
 'source.spm',
 'target.spm',
 'added_tokens.json'  too much files. What should I do?

**Comment by FFengIll** [comment]
vocab.json can be used  to load and parse into tokenizer info.

**Comment by tqchen** [comment]
Seems one common approach so far is to convert the other tokenizer format into HF's tokenizer.json format
