### ISSUE TITLE
is there any plan to support Tiktoken?

### ISSUE THREAD

**Issue by Jasonsey** [mlc-ai/tokenizers-cpp#23]
I am trying to make mlc to support Qwen, but the model's tokenizer use tiktoken developed by openai, which is not supported by this repo now? So is there any plan for this feature?

**Comment by tqchen** [comment]
As of now we don't have planned effort yet, contribution is welcomed

**Comment by gaokao123** [comment]
@Jasonsey for tiktoken of qwen, Is there a solution now?

**Comment by Jasonsey** [comment]
> @Jasonsey for tiktoken of qwen, Is there a solution now?

Currently, we can use the mlc chat to convert Qwen'tiktoken to this repo's tokenizer format.

**Comment by Jasonsey** [comment]
> @Jasonsey for tiktoken of qwen, Is there a solution now?

Currently, we can use the mlc chat to convert Qwen'tiktoken to this repo's tokenizer format.
