### ISSUE TITLE
Can't support cross build on Linux

### ISSUE THREAD

**Issue by SakuragiJump** [mlc-ai/tokenizers-cpp#24]
when I want to build a aarch64 on x86_64 host，cargo build will not accept a optioin "--target aarch64-unknown-linux-gnu" and build a x86_64 one，so cross build will not work out。

**Comment by mayway530** [comment]
同样问题，期待解决

**Comment by Abhishek8394** [comment]
I was able to resolve this issue and can help if you share your build info. For starters, try the target string `aarch64-linux-android`

**Comment by Abhishek8394** [comment]
You would also be better off by linking to android ndk toolchain file. Guide at https://developer.android.com/ndk/guides/cmake#file.

**Comment by tqchen** [comment]
@Abhishek8394 thanks for your info, do you mind send a PR to the README to enhance build guide?

**Comment by Abhishek8394** [comment]
Sure, I'll make a PR.
