### ISSUE TITLE
example.cc running error

### ISSUE THREAD

**Issue by zhaoxuejun1234** [mlc-ai/tokenizers-cpp#53]
Hi,
    I'm trying the example.cc with a downloaded huggingface tokenizer.json. It came up with following when running. Nothing but only the huggingface tokenizer.json is changed in the source code. The downloaded json file is attached. I hope you have some time for this issue.
[tokenizer.json](https://github.com/user-attachments/files/18253311/tokenizer.json)

Tokenizer: Huggingface
thread '<unnamed>' panicked at src/lib.rs:26:50:
called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum ModelWrapper", line: 483534, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x555dfeceee0a - std::backtrace_rs::backtrace::libunwind::trace::h99efb0985cae5d78
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x555dfeceee0a - std::backtrace_rs::backtrace::trace_unsynchronized::he2c1aa63b3f7fad8
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555dfeceee0a - std::sys::backtrace::_print_fmt::h8a221d40f5e0f88b
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:66:9
   3:     0x555dfeceee0a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:39:26
   4:     0x555dfed3c34b - core::fmt::rt::Argument::fmt::h5da9c218ec984eaf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/rt.rs:177:76
   5:     0x555dfed3c34b - core::fmt::write::hf5713710ce10ff22
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/fmt/mod.rs:1178:21
   6:     0x555dfece3403 - std::io::Write::write_fmt::hda708db57927dacf
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/io/mod.rs:1823:15
   7:     0x555dfecf1602 - std::sys::backtrace::BacktraceLock::print::hbcdbec4d97c91528
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:42:9
   8:     0x555dfecf1602 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:266:22
   9:     0x555dfecf126e - std::panicking::default_hook::h81c8cd2e7c59ee33
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:293:9
  10:     0x555dfecf1f4f - std::panicking::rust_panic_with_hook::had2118629c312a4a
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:797:13
  11:     0x555dfecf1c03 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:664:13
  12:     0x555dfecef2e9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
  13:     0x555dfecf18c4 - rust_begin_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
  14:     0x555dfeabd055 - core::panicking::panic_nounwind_fmt::runtime::h1c669551f619867f
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:112:18
  15:     0x555dfeabd055 - core::panicking::panic_nounwind_fmt::hc0ae93930ea8f76c
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:122:5
  16:     0x555dfeabd0e2 - core::panicking::panic_nounwind::h9f485ff9b02bac75
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:221:5
  17:     0x555dfeabd306 - core::panicking::panic_cannot_unwind::hea865182d7ce50af
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:310:5
  18:     0x555dfeae037b - tokenizers_new_from_str
  19:     0x555dfeaca040 - _ZN10tokenizers9Tokenizer12FromBlobJSONERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  20:     0x555dfeac6613 - _Z27HuggingFaceTokenizerExamplev
  21:     0x555dfeac69ac - main
  22:     0x7f5fe9cb9083 - __libc_start_main
                               at /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
  23:     0x555dfeac5a8e - _start
  24:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
build_and_run.sh: line 30: 3322201 Aborted                 (core dumped) ./build/example

**Comment by TriLoo** [comment]
same error

**Comment by zhaoxuejun1234** [comment]
> same error

Hi, may I know which repo's json are you loading?

**Comment by zhaoxuejun1234** [comment]
This may related to the merge rule format of specific tokenizer.json

**Comment by zhaoxuejun1234** [comment]
This issue has been solved by modify json format. Thank you!

**Comment by TriLoo** [comment]
> This issue has been solved by modifying json format. Thank you!

hi @zhaoxuejun1234 , I'm using Qwen2 tokenizer.

could you tell me how to solve this error? thanks

**Comment by zhaoxuejun1234** [comment]
> > This issue has been solved by modifying json format. Thank you!
> 
> hi @zhaoxuejun1234 , I'm using Qwen2 tokenizer.
> 
> could you tell me how to solve this error? thanks

I just checked the Qwen2 tokenizer. Our issues may not the same. My tokenizer issue related to the nesting lists format of key "merges". I attach the code for modifying the tokenizer in case you need.

def change_merges(path,new_path):
    with open(path, 'r') as file:
        data = json.load(file)
        merges = data.get('model', []).get('merges', [])
        new_merges = [' '.join(sublist) for sublist in merges]
    print(merges[1],"   ",merges[2])
    print(new_merges[1],"   ",new_merges[2])
    data['model']['merges'] = new_merges
    with open(new_path, 'w',encoding='utf-8') as file:
        json.dump(data, file, ensure_ascii=False,indent=4)

**Comment by TriLoo** [comment]
got it, thanks
